Runtime Error
Error: ./src/components/google-map.tsx:4:1
Export useJsapiLoader doesn't exist in target module
  2 |
  3 | import { useState, useEffect, useRef, useCallback } from 'react';
> 4 | import { GoogleMap, LoadScript, Marker, useJsapiLoader } from '@react-google-maps/api';
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  5 | import { Coordinate } from '@/services/open-route-service';
  6 | import { Button } from '@/components/ui/button';
  7 | import { Icons } from '@/components/icons';

The export useJsapiLoader was not found in module [project]/node_modules/@react-google-maps/api/dist/esm.js [app-client] (ecmascript).
Did you mean to import useJsApiLoader?
All exports of the module are statically known (It doesn't have dynamic exports). So it's known statically that the requested export doesn't exist.

Show More
Call Stack
7

Show 5 ignore-listed frame(s)
<unknown>
error: ./src/components/google-map.tsx (4:1)
<unknown> (Error:
./src/components/google-map.tsx (4:1)